apiVersion: external-secrets.io/v1 
kind: ExternalSecret
metadata:
  name: rds-external-secret
  namespace: cricket-shop
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: rds-secret
  dataFrom:
    - extract:
        key: "arn:aws:secretsmanager:ap-south-1:216569733367:secret:rds!db-ebd02da3-9bc8-4766-ab57-94af6f4d7f09-VF1BQ5"
