apiVersion: external-secrets.io/v1 
kind: ExternalSecret
metadata:
  name: rds-external-secret
  namespace: cricket-shop
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: rds-secret
  dataFrom:
    - extract:
        key: "arn:aws:secretsmanager:ap-south-1:216569733367:secret:rds!db-f1dbc046-2d3a-4d6e-b778-4cabe07b557c-6pgOLC"
