apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-external-secret
  namespace: cricket-shop
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: rds-secret
  dataFrom:
    - extract:
        key: "<STEP-3-లో-వచ్చిన-rds_secret_arn-పేస్ట్-చెయ్యి>"
